apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: syncs.extension.shepherd
spec:
  additionalPrinterColumns:
  - JSONPath: .status.restorePhase
    name: Status
    type: string
  group: extension.shepherd
  names:
    kind: Sync
    plural: syncs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupEnv:
              type: string
            backupSpec:
              properties:
                mysql:
                  description: MySQL databases which will be backed up.
                  type: object
                volumes:
                  description: Volumes which will be backed up.
                  type: object
              type: object
            restoreEnv:
              type: string
            restoreSpec:
              description: We can use the backup spec for the restore spec as we just
                need volumes/dbs.
              properties:
                mysql:
                  description: MySQL databases which will be backed up.
                  type: object
                volumes:
                  description: Volumes which will be backed up.
                  type: object
              type: object
            site:
              description: Correlates to node ids in shepherd.
              type: string
          required:
          - site
          - backupEnv
          - restoreEnv
          - backupSpec
          - restoreSpec
          type: object
        status:
          properties:
            backupName:
              type: string
            backupPhase:
              type: string
            completionTime:
              format: date-time
              type: string
            restoreName:
              type: string
            restorePhase:
              type: string
            startTime:
              format: date-time
              type: string
          required:
          - backupPhase
          - restorePhase
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
