apiVersion: extension.shepherd/v1
kind: Restore
metadata:
  name: test-restore
  labels:
    site: '123'
spec:
  backupName: abcd969xcz
status:
  phase: New|InProgress|Failed|Completed
  startTimestamp: '2018-11-21T00:16:23Z'
  completionTimestamp: '2018-11-21T00:16:43Z'