apiVersion: extension.shepherd/v1
kind: Restore
metadata:
  name: test-restore
  labels:
    site: '123'
    environment: 123
spec:
  backupName: abcd969xcz
  volumes:
    shared:
      claimName: node-123-shared
  mysql:
    default:
      secret:
        name: node-123
        keys:
          username: DATABASE_USER
          password: DATABASE_PASSWORD
          database: DATABASE_NAME
          hostname: DATABASE_HOST
          port: DATABASE_PORT
status:
  startTimestamp: '2018-11-21T00:16:23Z'
  completionTimestamp: '2018-11-21T00:16:43Z'
  phase: New|InProgress|Failed|Completed
